spring:
  application:
    name: excel2db
  datasource:
    url: jdbc:mysql://10.29.79.58:23308/his?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: user_dev
    password: MsupDQQc0G7QHB
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

server:
  port: 10001

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.deaifish.excel2db.bean
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置
excel2db:
  config:
    language:
      file-name: language_template
